#To take month value in numeric formate and display number of days in it.
x=int(input("Enter month number"))
if x==1:
    print("%d Month is JANUARY"%x)
    print("NUMBER OF DAYS IS 31")
elif x==2:
    print("%d Month is FEBRUARY"%x,"NUMBER OF DAYS IS 28",sep="/")
elif x==3:
    print("%d Month is MARCH"%x)
    print("NUMBER OF DAYS IS 30")
elif x==4:
    print("%d Month is APRIL"%x)
    print("NUMBER OF DAYS IS 31")
elif x==5:
    print("%d Month is MAY"%x)
    print("NUMBER OF DAYS IS 30")
elif x==6:
    print("%d Month is JUNE"%x)
    print("NUMBER OF DAYS IS 31")
elif x==7:
    print("%d Month is JULY"%x)
    print("NUMBER OF DAYS IS 30")
elif x==8:
    print("%d Month is AUGUST"%x)
    print("NUMBER OF DAYS IS 31")
elif x==9:
    print("%d Month is SEPTEMBER"%x)
    print("NUMBER OF DAYS IS 30")
elif x==10:
    print("%d Month is OCTOBER"%x)
    print("NUMBER OF DAYS IS 31")
elif x==11:
    print("%d Month is NOVEMBER"%x)
    print("NUMBER OF DAYS IS 30")
elif x==12:
    print("%d Month is DECEMBER"%x)
